config/routes.rb
Mybasic::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "registrations"} 

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_scope :user do
    match "awaiting_confirmation", :to => "registrations#awaiting_confirmation", :via => [:get], :as => "awaiting_confirmation"
  end

  namespace :admin do
    root :to => "base#index"
    resources :users do
      get 'roles', :on => :member
      post 'assign_roles', :on => :member
      post 'lock', :on => :member
      post 'unlock', :on => :member
    end
    resources :roles do
      get 'permissions', :on => :member
      post 'assign_permissions', :on => :member
    end

    resources :permissions
  end

  root :to => 'home#index'

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  # attr_accessible :title, :body
  has_and_belongs_to_many :roles, :join_table => 'roles_permissions'
end

app/controllers/admin/permissions_controller.rb
# encoding: utf-8
class Admin::PermissionsController < Admin::BaseController
  before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  load_and_authorize_resource
  # GET /admin/permissions
  # GET /admin/permissions.json
  def index
    @admin_permissions = Permission.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_permissions }
    end
  end

  # GET /admin/permissions/1
  # GET /admin/permissions/1.json
  def show
    @admin_permission = Permission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_permission }
    end
  end

  # GET /admin/permissions/new
  # GET /admin/permissions/new.json
  def new
    @admin_permission = Permission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_permission }
    end
  end

  # GET /admin/permissions/1/edit
  def edit
    @admin_permission = Permission.find(params[:id])
  end

  # POST /admin/permissions
  # POST /admin/permissions.json
  def create
    @admin_permission = Permission.new(params[:permission])

    respond_to do |format|
      if @admin_permission.save
        format.html { redirect_to admin_permission_path(@admin_permission), notice: 'Permission was successfully created.' }
        format.json { render json: @admin_permission, status: :created, location: @admin_permission }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/permissions/1
  # PUT /admin/permissions/1.json
  def update
    @admin_permission = Permission.find(params[:id])

    respond_to do |format|
      if @admin_permission.update_attributes(params[:permission])
        format.html { redirect_to admin_permission_path(@admin_permission), notice: 'Permission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/permissions/1
  # DELETE /admin/permissions/1.json
  def destroy
    @admin_permission = Permission.find(params[:id])
    @admin_permission.destroy

    respond_to do |format|
      format.html { redirect_to admin_permissions_url, notice: 'Permission was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/views/admin/permissions/_form.html.erb
      

            <div class="grid_5">
                <div class="module">
                     <h2><span>权限管理</span></h2>
                        
                     <div class="module-body">
                        <%= form_for([:admin, @admin_permission]) do |f| %>
                          <% if @admin_permission.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(@admin_permission.errors.count, "error") %> prohibited this admin_permission from being saved:</h2>

                              <ul>
                              <% @admin_permission.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>
                        
                            <p>
                                <label>权限名</label>
                                <%= f.text_field :name , :class => "input-medium validate[required,minSize[6],maxSize[30],custom[onlyLetterNumber]]" %>
                            </p>
                            <p>
                                <label>资源类</label>
                                <%= f.text_field :subject_class , :class => "input-medium validate[required,maxSize[30],custom[onlyLetterNumber]]" %>
                            </p>
                            <p>
                                <label>操作点</label>
                                <%= f.text_field :action , :class => "input-mediumm validate[required,maxSize[30],custom[onlyLetterNumber]]" %>
                            </p>
                            <p>
                                <label>操作描述</label>
                                <%= f.text_field :description , :class => "input-medium validate[required,maxSize[30],custom[onlyLetterNumber]]" %>
                            </p>
                            
                            <fieldset>
                                <input class="submit-green" type="submit" value="Submit" /> 
                                <input class="submit-gray" type="submit" value="Cancel" />
                            </fieldset>
                        <% end %>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>

app/views/admin/permissions/edit.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#edit_permission_<%= @permission.id %>").validationEngine();
  });

</script> 

			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_permissions_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <a href="<%= admin_permission_path(@role) %>" class="button">
                          <span>查看</span>
                        </a>
                    </div>
                    
                    
                    
                </div>
            </div>

<%= render 'form' %>

app/views/admin/permissions/index.html.erb
        <!-- Initiate tablesorter script -->
        <script type="text/javascript">
            $(document).ready(function() { 
                $("#myTable") 
                .tablesorter({
                    // zebra coloring
                    widgets: ['zebra'],
                    // pass the headers argument and assing a object 
                    headers: { 
                        // assign the sixth column (we start counting zero) 
                        6: { 
                            // disable it by setting the property sorter to false 
                            sorter: false 
                        } 
                    }
                });
            //.tablesorterPager({container: $("#pager")}); 
        }); 
        </script>

            <div class="grid_12">
                
                <div class="bottom-spacing">
                
                    <!-- Button -->
                    <div class="float-left">
                        <a href="<%= new_admin_permission_path %>" class="button">
                          <span>新建权限<img src="<%= Xmcrm::Application.config.staticfile_server_url %>admin_style/images/plus-small.gif" width="12" height="9" alt="New article" /></span>
                        </a>
                    </div>
                    
                    
                    
                </div>
                
                
                <!-- Example table -->
                <div class="module">
                  <h2><span>权限管理</span></h2>
                    
                    <div class="module-table-body">

                        <table id="myTable" class="tablesorter">
                          <thead>
                                <tr>
                                    <th style="width:5%">ID</th>
                                    <th style="width:20%">权限名称</th>
                                    <th style="width:21%">资源</th>
                                    <th style="width:13%">操作点</th>
                                    <th style="width:13%">操作描述</th>
                                    <th style="width:13%">资源id</th>
                                    <th style="width:15%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @admin_permissions.each do |permission| %>
                                <tr>
                                    <td class="align-center"><%= permission.id %></td>
                                    <td><%= link_to permission.name, [:admin, permission] %></td>
                                    <td><%= permission.subject_class %></td>
                                    <td><%= permission.action %></td>
                                    <td><%= permission.description %></td>
                                    <td><%= permission.subject_id %></td>
                                    <td>
                                      <%= link_to '查看', admin_permission_path(permission) %> |
                                      <%= link_to "编辑", edit_admin_permission_path(permission) %> |
                                      <%= link_to "删除", admin_permission_path(permission), :method => :delete, :confirm => "你确定要删除此权限?" %>
                                    </td>
                                </tr> 
                                <% end %>                             
                            </tbody>
                        </table>
                        
                        <div style="clear: both"></div>
                     </div> <!-- End .module-table-body -->
                </div> <!-- End .module -->
                
                <div style="clear: both"></div>

                <div class="apple_pagination">
                    <%=h will_paginate @admin_permissions, :previous_label => '上一页',  :next_label => '下一页'%>
                </div>
                
                

                
            </div> <!-- End .grid_12 -->
            <div style="clear: both"></div>

app/views/admin/permissions/new.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#new_permission").validationEngine();
  });

</script> 

			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_permissions_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>
                    
                    
                    
                </div>
            </div>
<%= render 'form' %>

app/views/admin/permissions/show.html.erb
			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_permissions_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <a href="<%= edit_admin_permission_path(@permission) %>" class="button">
                          <span>编辑</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <%= link_to admin_permission_path(@permission), :method => :delete,
:confirm => "你确定要删除此权限?" , :class => 'button' do %>
						<span>删除权限</span>
						<% end %>
                    </div>
                    
                    
                    
                </div>
            </div>

			<div class="grid_5">

                <div class="module">
                     <h2><span>查看权限 <%= @permission.name %></span></h2>
                        
                     <div class="module-body">
                        <p>
							<div>权限名称:<%= @permission.name %></div>
						</p>
						<p>
							<div>描述:<%= @permission.description %></div>
						</p>
						<p>
							<div>资源:<%= @permission.subject_class %></div>
						</p>
						<p>
							<div>资源操作点:<%= @permission.action %></div>
						</p>
						<p>
							<div>资源id:<%= @permission.subject_id %></div>
						</p>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>