config/routes.rb
Mybasic::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "registrations"} 

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_scope :user do
    match "awaiting_confirmation", :to => "registrations#awaiting_confirmation", :via => [:get], :as => "awaiting_confirmation"
  end

  namespace :admin do
    root :to => "base#index"
    resources :users do
      get 'roles', :on => :member
      post 'assign_roles', :on => :member
      post 'lock', :on => :member
      post 'unlock', :on => :member
    end
    resources :roles do
      get 'permissions', :on => :member
      post 'assign_permissions', :on => :member
    end

    resources :permissions
  end

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles, :join_table => 'users_roles'
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :last_sign_in_at
  # attr_accessible :title, :body

  if Rails.env.production?
    attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :confirmed_at, :last_sign_in_at
  else
    attr_accessible :name, :email, :password, :password_confirmation, :remember_me,  :confirmation_token,
      :admin, :sign_in_count, :password_salt, :confirmed_at, :confirmation_sent_at, :created_at, :updated_at,
      :encrypted_password, :last_sign_in_at
  end
end

app/controllers/admin/users_controller.rb
# encoding: utf-8
class Admin::UsersController < Admin::BaseController
  before_filter :authenticate_user!
  # 两种验证方式 前面会加载model 后面的不会加载model
  load_and_authorize_resource
  before_filter :find_user, :only => [:show, :edit, :update, :destroy, :activity]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.order("created_at desc").paginate(:page => params[:page], :per_page => 20)
  end
  
  # 新建用户
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    # 手动验证 跳过验证,验证时间会被设定为当前创建的时间
    @user.skip_confirmation!
    if @user.save
      flash[:notice] = "用户创建成功."
      redirect_to admin_users_path
    else
      flash[:alert] = "用户创建失败."
      render :action => "new"
    end
  end
  
  # 显示用户
  def show
    
  end
  
  # 编辑用户
  def edit
    
  end
  
  # 完成编辑用户
  def update
    # 如果密码留空,就删除密码
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update_attributes(params[:user])
      flash[:notice] = "成功编辑用户."
      redirect_to admin_users_path
    else
      flash[:alert] = "编辑用户失败."
      render :action => "edit"
    end
  end
  
  # 删除用户操作
  def destroy
    if @user == current_user
      flash[:alert] = "你不能删除你自己!"
    else
      @user.destroy
      flash[:notice] = "用户已经成功删除."
    end
    redirect_to admin_users_path
  end

  # 锁定用户
  def lock
    if @user == current_user
      flash[:alert] = "你不能锁定你自己!"
    else
      @user.lock_access!
      flash[:notice] = "用户已经成功锁定."
    end    
    redirect_to :back
  end

  # 解锁用户
  def unlock  
    @user.unlock_access!
    flash[:notice] = "用户已经成功解锁." 
    redirect_to :back
  end


  # 查看所有角色
  def roles
    @user = User.find(params[:id])
    @roles_all = Role.all
    @roles = @user.roles
  end
  # 保存更新角色
  def assign_roles
    @user = User.find(params[:id])
    # 拿出此次得到角色数组
    role_ids = params[:role_ids]
    # 删除原来所有的关系
    @user.roles.delete(@user.roles)
    if not role_ids.nil?
      role_ids.each do |role_id| 
        role = Role.find_by_id(role_id)
        @user.roles << role
        # unless @user.roles.include? role
        #   @user.roles << role
        # end     
      end
    end
    redirect_to admin_user_path(@user)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

end

app/views/admin/users/_form.html.erb
            <div class="grid_5">
                <div class="module">
                     <h2><span>用户管理</span></h2>
                        
                     <div class="module-body">
                        <%= form_for([:admin, @user]) do |f| %>
                        	<% if @user.errors.any? %>
    						    <div id="error_explanation">
    						      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this role from being saved:</h2>

    						      <ul>
    						      <% @user.errors.full_messages.each do |msg| %>
    						        <li><%= msg %></li>
    						      <% end %>
    						      </ul>
    						    </div>
    						    
    						  <% end %>
                        
                        	<p>
                                <label>用户名</label>
                                <%= f.text_field :username , :class => "input-medium validate[required,minSize[2],maxSize[30]" %>
                            </p>
                            <p>
                                <label>电子邮件</label>
                                <%= f.email_field :email , :class => "input-medium validate[required,maxSize[50],custom[email]]" %>
                            </p>

                            <p>
                                <label>密码</label>
                                <%= f.password_field :password, :class => "input-medium validate[required,minSize[6],maxSize[30]]" %>
                            </p>
                            <p>
                                <label>密码确认</label>
                                <%= f.password_field :password_confirmation, :class => "input-medium validate[required,minSize[6],maxSize[30],equals[user_password]]" %>
                            </p>
                            
                            <fieldset>
                                <input class="submit-green" type="submit" value="Submit" /> 
                                <input class="submit-gray" type="submit" value="Cancel" />
                            </fieldset>
                        <% end %>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>

app/views/admin/users/edit.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#edit_user_<%= @user.id %>").validationEngine();
  });

</script> 

			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_users_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <a href="<%= admin_user_path(@user) %>" class="button">
                          <span>查看</span>
                        </a>
                    </div>
                    
                    
                    
                </div>
            </div>

<%= render 'form' %>

app/views/admin/users/index.html.erb
            <div class="grid_12">
                
                <div class="bottom-spacing">
                
                    <!-- Button -->
                    <div class="float-left">
                        <a href="<%= new_admin_user_path %>" class="button">
                          <span>新建用户</span>
                        </a>
                    </div>
                    
                    
                    
                </div>
                
                
                <!-- Example table -->
                <div class="module">
                  <h2><span>用户管理</span></h2>
                    
                    <div class="module-table-body">
                        <table id="myTable" class="tablesorter">
                          <thead>
                                <tr>
                                    <th style="width:5%">ID</th>
                                    <th style="width:15%">姓名</th>
                                    <th style="width:15%">邮箱</th>
                                    <th style="width:5%">验证</th>
                                    <th style="width:12%">创建日期</th>
                                    <th style="width:12%">最后更新</th>
                                    <th style="width:12%">最后登录</th>
                                    <th style="width:20%">操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @users.each do |user| %>
                                <tr>
                                    <td class="align-center"><%= user.id %></td>
                                    <td><a href=""><%= link_to user.username, [:admin, user] %></a></td>
                                    <td><%= link_to user.email, [:admin, user] %></td>
                                    <td><%= user.confirmed? ? '已验证' : '未验证' %></td>
                                    <td><%= user.created_at.strftime('%Y-%m-%d %H:%M') %></td>
                                    <td><%= user.updated_at.strftime('%Y-%m-%d %H:%M') %></td>
                                    <td><%= user.last_sign_in_at.nil? ? '从未登录' : user.last_sign_in_at.strftime('%Y-%m-%d %H:%M') %></td>
                                    <td>
                                      <%= link_to "编辑", edit_admin_user_path(user) %> |
                                      <%= link_to "角色分配", roles_admin_user_path(user) %> |
                                      <%= link_to "删除", admin_user_path(user), :method => :delete, :confirm => "你确定要删除此用户?" %> | 
                                        <% if user.access_locked? %>
                                            <%= link_to "解锁", unlock_admin_user_path(user), :method => :post,
                                            :confirm => "你确定要解锁此用户?" %>
                                        <% else %>
                                            <%= link_to "锁定", lock_admin_user_path(user), :method => :post,
                                            :confirm => "你确定要锁定用户?" %>
                                        <% end %>
                                    </td>
                                </tr> 
                                <% end %>                             
                            </tbody>
                        </table>
                        
                        <div style="clear: both"></div>
                     </div> <!-- End .module-table-body -->
                </div> <!-- End .module -->
                
                <div style="clear: both"></div>

                <div class="apple_pagination">
                    <%=h will_paginate @users, :previous_label => '上一页',  :next_label => '下一页'%>
                </div>
                
                

                
            </div> <!-- End .grid_12 -->
            <div style="clear: both"></div>

app/views/admin/users/new.html.erb
<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function(){
    // binds form submission and fields to the validation engine
    jQuery("#new_user").validationEngine();
  });

</script>			

			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_users_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>
                    
                    
                    
                </div>
            </div>

<%= render 'form' %>

app/views/admin/users/roles.html.erb
			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_users_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>

                    
                    
                    
                    
                </div>
            </div>

			<div class="grid_5">

                <div class="module">
                     <h2><span>给用户 <%= @user.username %> 分配角色</span></h2>
                        
                     <div class="module-body">
                        <%= form_tag(assign_roles_admin_user_path, :method => "post") do %>
							<p>角色:</p>
							<% @roles_all.each do |role| %>	
							<span>
						  	<%= check_box_tag('role_ids[]', role.id, @roles.include?(role), :style => "float:left;vertical-align: middle;margin-right: 6px;") %>
							<%= label :role_id, role.rolename %>
							</span>
							<% end %>
							<br>
							<%= submit_tag '保存'%>
						<% end %>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>

app/views/admin/users/show.html.erb
			<div class="grid_12">
            	<div class="bottom-spacing">
                
                    
                    <div class="float-left">
                        <a href="<%= admin_users_path %>" class="button">
                          <span>返回</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <a href="<%= edit_admin_user_path(@user) %>" class="button">
                          <span>编辑</span>
                        </a>
                    </div>

                    <div class="float-left">
                        <%= link_to admin_user_path(@user), :method => :delete,
:confirm => "你确定要删除此用户?" , :class => 'button' do %>
						<span>删除用户</span>
						<% end %>
                    </div>
                    
                    
                    
                </div>
            </div>

			<div class="grid_5">

                <div class="module">
                     <h2><span>查看用户 <%= @user.username %></span></h2>
                        
                     <div class="module-body">
                        <p>
							<div>姓名:<%= @user.username %></div>
						</p>
						<p>
							<div>邮箱:<%= @user.email %></div>
						</p>
						<p>
							<div>角色:
								<% @user.roles.each do |role| %>
								<%= role.rolename %>
								<% end %>

							</div>
						</p>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>